POST http://localhost:3030/auth/signup
content-type: application/json

{
    "email":"jazz@t.com",
    "password": "teaekdfdshfsd"
}

### Signin User
POST http://localhost:3030/auth/signin
content-type: application/json

{
    "email":"jazz@t.com",
    "password": "teaekdfdshfsd"
}

### get current user thats logged in
GET http://localhost:3030/auth/whoami
###  find one user
GET http://localhost:3030/auth/5

###  Sign out User 
POST http://localhost:3030/auth/signout

### Find all users with a given email
GET http://localhost:3030/auth?email=adrf@t.com

### Delete  user given id
DELETE http://localhost:3030/auth/2

### Update a user
PATCH http://localhost:3030/auth/4
content-type: application/json

{
    "email": "ksmasemula@gmail.com"
}